name: Release
on: 
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_RELEASE_KEY }}

      - name: Get release version
        id: release-version
        run: |
          VERSION=$(npx auto version)
          echo "Detected version: $VERSION"
          echo "::set-output name=version::$VERSION"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Auto release
        run: |
          npx auto shipit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to Docker Hub
        if: steps.release-version.outputs.version
        uses: docker/login-action@v2.0.0
        with:
          username: pleodeployments
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image and cache Docker image/layers.
      - name: Build Docker image
        if: steps.release-version.outputs.version
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.release-version.outputs.version }}
          load: true
          push: true
