name: Release
on: 
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Auto
        run: |
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.37.4/auto-linux.gz | gunzip > ~/auto
          chmod a+x ~/auto

      - name: Run Auto release
        run: |
          ~/auto shipit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: pleodeployments
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current version
        id: current-version
        run: |
          VERSION=$(~/auto info | sed -n 's/.*Current Version: //p')
          echo "Detected version: $VERSION"
          echo "::set-output name=version::$VERSION"
      
      # Build Docker image and cache Docker image/layers.
      - name: Build Docker image
        if: steps.current-version.outputs.version
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.current-version.outputs.version }}
          load: true
