name: Verify Release
# This verifies that a given PR has the required labels before merge into the default branch.
on:
  pull_request:
    types:
    - opened
    - edited
    - labeled
    - unlabeled
    - synchronize

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-release:
    name: Verify Release
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Verify PR labels
      id: verify_pr_labels
      uses: docker://agilepathway/pull-request-label-checker:latest
      with:
        one_of: major,minor,patch,internal
        repo_token: ${{ secrets.GITHUB_TOKEN }}
